version: "3.7"

services:
  django3:
    build: ./ServiceA
    tty: true
    ports:
      - 8081:8000
    volumes:
      - ./ServiceA:/srv/
    env_file:
      - conf/ServiceA.env
      - conf/secret.env
    depends_on:
      - datadog
    command: python manage.py runserver 0.0.0.0:8000

  fastapi:
    build: ./ServiceB
    ports:
      - 8082:8000
    volumes:
      - ./ServiceB:/srv/
    env_file:
      - conf/ServiceB.env
    depends_on:
      - datadog
    command: python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  datadog:
    image: gcr.io/datadoghq/agent:latest
    ports:
      - 8126:8126/tcp # Tracing Docker Applications
      - 8125:8125/udp # DogStatsD
    env_file:
      - conf/datadog.env
      - conf/dd_api_key.env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
