version: "3.7"

services:
  django3:
    build: ./ServiceA
    tty: true
    ports:
      - 8081:8000
    volumes:
      - "./ServiceA:/srv/"
    env_file:
      - conf/ServiceA.env
    command: python manage.py runserver 0.0.0.0:8000 --noreload
